name: client_components
description: An in-house collection of Angular Dart components used by Appfoundry clients
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin/client_components
version: 0.1.8
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.1
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  fo_components: ^2.0.0
  grid_css: ^2.0.1
  intl: ^0.16.1
  sass_builder: ^2.1.3
