name: client_components
description: An in-house collection of Angular Dart components used by Appfoundry clients
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://github.com/afpatmin/client_components
version: 0.1.7
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  angular_forms: ^2.1.3
  angular_router: ^2.0.0-alpha+23
  fo_components: ^1.7.5+3
  grid_css: ^1.0.0
  intl: ^0.15.8
  sass_builder: ^2.1.3