name: client_components
description: An in-house collection of Angular Dart components used by Appfoundry clients
publish_to: none
homepage: https://github.com/afpatmin/client_components
version: 0.1.8
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  angular_forms: ^4.0.0
  angular_router: ^3.0.0
  fo_components: ^3.0.1
  grid_css: ^3.0.0
  intl: ^0.17.0
  sass_builder: ^2.1.4
