name: client_components
description: An in-house collection of Angular Dart components used by Appfoundry clients
publish_to: none
homepage: https://github.com/afpatmin/client_components
version: 1.0.0
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  angular: ^7.0.2
  angular_forms: ^4.0.1
  angular_router: ^3.0.1
  fo_components: ^3.1.1
  sass_builder: ^2.1.4
